# Generated by Django 2.1.2 on 2018-10-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_id', models.CharField(max_length=20)),
                ('auth_pw', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('sex', models.IntegerField(default=0)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('join_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='info_id',
            field=models.ForeignKey(on_delete='CASCADE', to='rest.User_info'),
        ),
    ]
