# Generated by Django 2.1.1 on 2018-10-10 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='info_id',
        ),
    ]
