# Generated by Django 2.1.1 on 2018-10-11 07:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20181011_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_tendency',
            old_name='subject_id',
            new_name='tendency_id',
        ),
        migrations.AlterField(
            model_name='user_group',
            name='joined',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 10, 11, 7, 29, 29, 655446, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='user_group',
            unique_together={('user_id', 'group_id')},
        ),
        migrations.AlterUniqueTogether(
            name='user_subject',
            unique_together={('user_id', 'subject_id')},
        ),
        migrations.AlterUniqueTogether(
            name='user_tendency',
            unique_together={('user_id', 'tendency_id')},
        ),
    ]
