# Generated by Django 2.1.1 on 2018-10-11 07:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_auto_20181011_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_group',
            name='joined',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 10, 11, 7, 32, 51, 649692, tzinfo=utc)),
        ),
    ]
