# Generated by Django 2.1.1 on 2018-10-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_auth',
            name='user_pk',
        ),
    ]
